build.gradle
This configures gradle to publish to maven central using the https://github.com/gradle-nexus/publish-plugin/ plugin.
To publish to maven central, we needed to add a lot of stuff to our POM (license info, developer info, description, etc).
Also, we needed to configure signing for all our artifacts (fat jar, sources jar, javadoc jar, pom).
To publish a new version to a staging repo on maven central, run:
```
./gradlew publishToSonatype closeSonatypeStagingRepository
```
The release process will be documented in the README in the future
=> Configure publishing to maven central

src/main/java/com/incognia/AddressType.java, src/main/java/com/incognia/IncogniaAPI.java, src/main/java/com/incognia/PostTransactionRequestBody.java, src/main/java/com/incognia/TransactionAddress.java, src/main/java/com/incognia/TransactionAssessment.java, src/test/java/com/incognia/IncogniaAPITest.java, src/test/java/com/incognia/TokenAwareDispatcher.java, src/test/resources/post_transaction_response.json
This adds payment (registerPayment) and login (registerLogin) methods. They both call the same endpoint, but we want to make this distinction for our clients.
The methods also have overloads for optional parameters (like external id)
=> Add payment and login methods

src/main/java/com/incognia/FeedbackEvent.java, src/main/java/com/incognia/FeedbackIdentifiers.java, src/main/java/com/incognia/IncogniaAPI.java, src/main/java/com/incognia/NetworkingClient.java, src/main/java/com/incognia/ObjectMapperFactory.java, src/main/java/com/incognia/PostFeedbackRequestBody.java, src/main/java/com/incognia/TokenAwareNetworkingClient.java, src/test/java/com/incognia/IncogniaAPITest.java, src/test/java/com/incognia/TokenAwareDispatcher.java
This adds a method to call the feedback api. Its signature is quite different (it gets an object with optional ids, as there are too many ids).
We also needed some changes in the networking layer, to support post requests that do not return a body
=> Add register feedback method

build.gradle, src/main/java/com/incognia/NetworkingClient.java, src/main/java/com/incognia/TokenAwareNetworkingClient.java, src/test/java/com/incognia/TokenAwareDispatcher.java
- Read expiration from response json instead of decoding token
- Use token type from response json instead of hardcoding 'Bearer'
- Send grant_type=client_credentials in body for token requests
=> Full support for oauth client credentials flow

README.md
The addresses are instantiated but not passed to the api method.
=> docs(README): Fix call to registerPayment method

src/main/java/com/incognia/SignupAssessment.java, src/main/java/com/incognia/TransactionAssessment.java, src/test/java/com/incognia/IncogniaAPITest.java, src/test/resources/get_onboarding_response.json, src/test/resources/post_onboarding_response.json, src/test/resources/post_transaction_response.json
This PR Adds Device Id to the response of transactions and onboarding routes.
=> feat(SignupAssessment, TransactionAssessment): Adds Device Id To Responses

.github/dependabot.yml
Configures dependabot to:
- check for updates once a week
- open at most 20 PRs so it catches more updates at each run
- let GitHub choose assignees and reviewers
=> chore(dependabot): check for updates once a week

build.gradle
Since we removed the shadow config for our lib, dependencies were not being published correctly in the POM file. This fixes it by setting the maven publish plugin to get all java components for publishing (this includes dependencies correctly)
=> Fix dependency declarations

src/main/java/com/incognia/api/clients/ObjectMapperFactory.java
Use PropertyNamingStrategy.SNAKE_CASE instead of PropertyNamingStrategies.SNAKE_CASE for compatibility with older jackson versions
=> Improve compatibility with older jackson versions

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/onboarding/PostSignupRequestBody.java, src/main/java/com/incognia/onboarding/SignupAssessment.java, src/main/java/com/incognia/transaction/TransactionAssessment.java
Fix Installation ID Parsing: The PR enhances the parsing of the installation ID within the Post Onboarding and Transaction response.
Expanded Locations Data in Post-Signup Requests: Additionally, it extends the functionality of the PostSignupRequest by adding support for additional locations.
=> Fix installation-id parsing on response and additional locations post request

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/transaction/PostTransactionRequestBody.java, src/main/java/com/incognia/transaction/login/RegisterWebLoginRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java
Support web login via a new method: `registerWebLogin`, following the api design of our Node client.
=> Support web login

README.md, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/transaction/login/RegisterWebLoginRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java
As seen [here](https://dash.incognia.com/accounts-test/sandbox/api-reference#tag/Transactions/operation/transactions-post) for web, the installation id is not part of the request, since the sessionToken already has this data.
=> Remove installation id from register web login

src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/transaction/payment/RegisterPaymentRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java
For a time we are moving towards having policies for every type of transaction-org we have. We already implemented policies for login and sign up here. This PR brings policies to Payment as well.
Plus, this PR also brings minor changes and code organization missed on previous ones.
=> Adding policyId to Payment API. Plus minor documentation updates and code organization

src/main/java/com/incognia/api/clients/ObjectMapperFactory.java
We should not break json deserialization if a unknown field is introduced in the API response
=> Do not fail to deserialize response json when unknown fields are introduced

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/onboarding/RegisterSignupRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java, src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java, src/test/resources/post_onboarding_response_no_address.json
In our onboarding api, address is optional. In this lib, it was required.
This makes address nullable and adds proper testing
=> Support null address in RegisterSignupRequest

README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties
This adds a new artifact, `incognia-api-client-shaded`, published along with `incognia-api-client`. This new artifact shades dependencies to avoid dependency conflicts with commonly used libraries (jackson, okhttp).
=> Add shaded jar artifact along with regular jar

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/transaction/PostTransactionRequestBody.java, src/main/java/com/incognia/transaction/login/RegisterLoginRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java
I want to add custom_properties to transactions to support related_account_id.
=> Add custom properties to post transactions

README.md
The lib is no longer published on Maven Central, so this PR removes references to it in the README page and suggests getting it from Incognia's Maven repository
=> Remove references to Maven Central in README

build.gradle
In https://github.com/inloco/incognia-api-java/pull/227 pom generation was broken since we only included the jar as artifact. This fixes it by using `components.java`
=> Fix pom generation for non-shaded version

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/onboarding/PostSignupRequestBody.java, src/main/java/com/incognia/onboarding/RegisterSignupRequest.java, src/main/java/com/incognia/transaction/PostTransactionRequestBody.java, src/main/java/com/incognia/transaction/login/RegisterLoginRequest.java, src/main/java/com/incognia/transaction/payment/RegisterPaymentRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java, src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java
We are adding deviceOs and appVersion as an optional field to our Login, SignUp and Payment mobile endpoints
=> Add appVersion and deviceOs to request body for mobile Login/SignUp/Payment risk assessments

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/api/clients/NetworkingClient.java, src/main/java/com/incognia/common/utils/CustomOptions.java, src/test/java/com/incognia/api/IncogniaAPITest.java
This PR introduces configurable timeout for the Incognia API. If no timeout is set, the library will continue to follow the OKHttp default that is 10 seconds.
=> Adding configurable timeout for clients

src/main/java/com/incognia/transaction/payment/PaymentType.java
The `PaymentType.java` file was outdated. So we are adding current available payment types there.
=> Update PaymentType to match with current implementation

README.md, build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/api/clients/NetworkingClient.java, src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java, src/main/java/com/incognia/common/utils/CustomOptions.java, src/test/java/com/incognia/api/IncogniaAPITest.java
Adds connection pool configuration so we are able to set something other than OkHTTP default config.
Had to downgrade Mockito since version 5 is for Java >= 11 and the project is targeting Java 8 and also has GHA using Java 8, so Mockito 4 is the last version to support Java 8.
For `CustomOptions` instead of using `Optional.ofNullable` used Lombok to set the defaults and used primitives so nulls are not allowed. The defaults there, `timeoutMillis` is what we had before, `maxConnections` and `keepAliveSeconds` is what OkHTTP sets by default so we keep what was being set before the addition of those options.
Removed immediate execution of optional orElse.
Made OkHTTP client execute use try with resources so we are sure that the response is always closed.
Removed one map key iteration and …
=> Add Connection Pool Options

src/main/java/com/incognia/feedback/FeedbackEvent.java
A few standard feedback types that were previously missing from the Java API library were added, such as `reset` and `account_allowed`.
As this PR only adds a few constants to an existing `enum`, no additional tests were created. Existing tests were used to evaluate correctness.
=> chore: add feedback types

src/main/java/com/incognia/api/clients/NetworkingClient.java, src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java, src/main/java/com/incognia/api/clients/TokenProvider.java, src/main/java/com/incognia/api/clients/TokenResponse.java, src/test/java/com/incognia/api/IncogniaAPITest.java, src/test/java/com/incognia/api/clients/NetworkingClientTest.java, src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java, src/test/java/com/incognia/api/clients/TokenAwareNetworkingClientTest.java, src/test/java/com/incognia/api/clients/TokenProviderTest.java
As right now the Access Token refresh is a sync operation and not thread safe. Meaning that two threads or more trying to do a request at the same time will invoke the refresh token at the same time refreshing it more than needed. This PRs introduces changes to make the TokenResponse object volatile and lock mechanism since the Token expiration also needs to be change while updating the token.
Since most of the code/test didn't consider such condition it was required more changes to other classes and tests. A refactor was performed so we could have token awareness across threads.
Also, there was some unused code that I took the opportunity to remove.
=> Make Access Token thread safe/aware

src/main/java/com/incognia/transaction/payment/PaymentType.java
This commit adds the `boleto_bancario` payment type that was missing.
=> chore: add payment method type

build.gradle, src/main/java/com/incognia/api/IncogniaAPI.java, src/main/java/com/incognia/transaction/PostTransactionRequestBody.java, src/main/java/com/incognia/transaction/login/RegisterLoginRequest.java, src/test/java/com/incognia/api/IncogniaAPITest.java
Adds `related_account_id` field to the `registerLogin` request
=> feat: adds related_account_id to login requests
