src/main/java/com/incognia/IncogniaAPI.java
src/main/java/com/incognia/NetworkingClient.java
src/main/java/com/incognia/TokenAwareNetworkingClient.java
src/test/java/com/incognia/IncogniaAPITest.java
src/test/java/com/incognia/NetworkingClientTest.java
src/test/java/com/incognia/TokenAwareDispatcher.java
src/test/java/com/incognia/TokenAwareNetworkingClientTest.java
src/test/resources/get_onboarding_response.json

This adds the `getSignupAssessment` method to `IncogniaAPI`.
Some additions in networking classes were needed to support http GET method.

Add getSignupAssessment

---

.github/workflows/gradle-wrapper-validation.yaml

This adds gradle wrapper validation, to prevent malicious code injection via gradle wrapper. Check https://github.com/marketplace/actions/gradle-wrapper-validation for more detail.

Add gradle wrapper validation

---

src/main/java/com/incognia/FeedbackEvent.java

feat(FeedbackEvent): adds new feedback events

---

README.md
build.gradle

This PR bumps the version to a new major, called 2.0.0
This version is up to date and working with version 2.187.0 of the api

chore(README.md, build.gradle): updates to major version

---

README.md
build.gradle
src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
src/test/java/com/incognia/api/clients/NetworkingClientTest.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

Describe the big picture of your changes here to communicate to the reviewers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.
Attaching relevant documentation and/or mentioning related PRs is also helpful.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

refactor(TokenAwareNetworkingClient): changes route to be v2 token route

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/api/Region.java

This PR changes the maven repository to be our internal maven which we can have better control.

chore(build.gradle): changes repository

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/api/Region.java
src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
src/test/java/com/incognia/api/clients/NetworkingClientTest.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

This PR changes the base URL of the API.
we should always call api.incognia.com from now on.

refactor(Region.java): We no longer have the need to use two different endpoints

---

build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/api/clients/NetworkingClient.java
src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
src/test/java/com/incognia/api/IncogniaAPITest.java

This PR adds support to dry run parameter in Feedback API

Adds dry run parameter in Feedback API

---

build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/api/clients/NetworkingClient.java
src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
src/main/java/com/incognia/common/ReasonCode.java
src/main/java/com/incognia/feedback/FeedbackEvent.java
src/test/java/com/incognia/api/IncogniaAPITest.java

This PR adds new feedbacks and reasons
See [documentation](http://docs.incognia.com/) for more details

Adds custom feedback event types

---

README.md

Add format to some of readme code

docs(readme): add format

---

.gitignore
build.gradle
src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

This PR adds header information to indicate requests from java wrapper. Header information follows the format
`<library-name>/<library-version> (<os-name> <os-version> <os-arch>) <language-name>/<language-version>`
A `ProjectVersion.java` file is created with a `PROJECT_VERSION` field before compilation to access the library version

Add user agent header

---

src/main/java/com/incognia/common/ReasonCode.java
src/main/java/com/incognia/feedback/FeedbackEvent.java

This PR adds the custom churn debt 20d feedback to the list of feedback and reasons

Add custom churn debt 20d feedback and reasons

---

src/main/java/com/incognia/common/ReasonCode.java
src/main/java/com/incognia/feedback/FeedbackEvent.java

This PR refactors `custom_churn_debt20d` feedback event to `custom_debt_churn_20d` to be according to offline database

Refactor custom_churn_debt20d to custom_debt_churn_20d

---

build.gradle

Some users using kotlin reported some issues, so we are removing this
for now.

Remove shadow jar

---

src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/onboarding/PostSignupRequestBody.java
src/main/java/com/incognia/onboarding/RegisterSignupRequest.java
src/test/java/com/incognia/api/IncogniaAPITest.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

Support new ids for signup requests, recently added to the API

Support new ids for signup requests

---

.github/CODEOWNERS

Use owners' group instead of individual handles as code owners.

chore(CODEOWNERS): set to @inloco/incognia-owners

---

src/main/java/com/incognia/common/AdditionalLocation.java
src/main/java/com/incognia/onboarding/RegisterSignupRequest.java

Add additional locations support to signup request

Add additional locations support in signup request

---

src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

Rename variable to avoid the following confusion of the dispatcher
https://github.com/inloco/incognia-api-java/security/code-scanning/3

Rename field to avoid dispatcher confusion

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/onboarding/PostSignupRequestBody.java
src/main/java/com/incognia/onboarding/RegisterWebSignupRequest.java
src/main/java/com/incognia/transaction/PostTransactionRequestBody.java
src/main/java/com/incognia/transaction/login/RegisterLoginRequest.java
src/main/java/com/incognia/transaction/login/RegisterWebLoginRequest.java
src/test/java/com/incognia/api/IncogniaAPITest.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

Adding policy to login and adding web signup endpoint

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/feedback/FeedbackIdentifiers.java
src/main/java/com/incognia/feedback/PostFeedbackRequestBody.java
src/test/java/com/incognia/api/IncogniaAPITest.java

Add session token to feedback

---

README.md

Web Signup method should be `registerWebSignup` instead of `registerSignup`.

Fix Web Signup usage description on README

---

src/test/resources/post_transaction_response.json

This tests the fix for unknown fields provided in
https://github.com/inloco/incognia-api-java/pull/215

test: add unknown field to mocked response

---

README.md
src/main/java/com/incognia/api/IncogniaAPI.java
src/test/java/com/incognia/api/IncogniaAPITest.java

This essentially makes `IncogniaAPI` a singleton.
This is a breaking change. `README.md` has been updated accordingly.

Create IncogniaAPI via static methods

---

README.md
build.gradle

The last change adding singletons to API wasnt been published. So we create a new version that includes it.

Update version v2.9.0

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/feedback/FeedbackIdentifiers.java
src/main/java/com/incognia/feedback/PostFeedbackRequestBody.java
src/main/java/com/incognia/onboarding/PostSignupRequestBody.java
src/main/java/com/incognia/onboarding/RegisterSignupRequest.java
src/main/java/com/incognia/onboarding/RegisterWebSignupRequest.java
src/main/java/com/incognia/transaction/PostTransactionRequestBody.java
src/main/java/com/incognia/transaction/login/RegisterLoginRequest.java
src/main/java/com/incognia/transaction/login/RegisterWebLoginRequest.java
src/main/java/com/incognia/transaction/payment/RegisterPaymentRequest.java
src/test/java/com/incognia/api/IncogniaAPITest.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

> [!IMPORTANT]  
> This PR reverts the breaking changes made in https://github.com/inloco/incognia-api-java/pull/240
Give support to requestToken in all api flows as requested.

feat: Give support to requestToken

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/test/java/com/incognia/api/IncogniaAPITest.java

This PR includes the changes made in https://github.com/inloco/incognia-api-java/pull/240 and https://github.com/inloco/incognia-api-java/pull/248. To be released in version 3.0.0

Request token support and IncogniaAPI as singleton

---

README.md
build.gradle

Updates version to 3.1.0

---

README.md
build.gradle
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/onboarding/PostSignupRequestBody.java
src/main/java/com/incognia/onboarding/RegisterSignupRequest.java
src/test/java/com/incognia/api/IncogniaAPITest.java
src/test/java/com/incognia/api/clients/TokenAwareDispatcher.java

Adds the custom_properties field to Sign Up request.
Update release to 2.11.0.

Add support to custom properties on v2.11.0.

---

README.md

Minor adjustment on the README

Adding long (L) to define the number

---

.github/workflows/test.yaml
src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/common/Location.java
src/main/java/com/incognia/transaction/PostTransactionRequestBody.java
src/main/java/com/incognia/transaction/login/RegisterLoginRequest.java
src/test/java/com/incognia/api/IncogniaAPITest.java

This PR enables the API Java to receive the location field on the Login API Request.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Adding location API Field to the lib

---

.sdkmanrc

Adds the SDK Man file for easy Java configuration.

Adding SDKMan File

---

src/main/java/com/incognia/common/ReasonCode.java
src/main/java/com/incognia/feedback/FeedbackEvent.java

Adds missing custom cancellation feedback type
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Adding custom cancellation Feedback type

---

src/main/java/com/incognia/api/IncogniaAPI.java
src/main/java/com/incognia/transaction/login/RegisterWebLoginRequest.java
src/test/java/com/incognia/api/IncogniaAPITest.java

Adds the `customProperties` field to the web login method

feat: adds custom properties to web login request
